name: levelup
description: "Level Up"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  go_router: ^13.2.0
  flutter_bloc: ^8.1.4
  meta: ^1.11.0
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.4
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.6
  mocktail: ^1.0.3

flutter:

  uses-material-design: true
  assets:
    - assets/

